language: cpp
compiler:
- clang
os: linux
dist: trusty
git:
  submodules: false
before_install:
- echo $LANG
- echo $LC_ALL
- echo $TRAVIS_OS_NAME
- uname -s
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- sed -e 's/git@github.com:/git:\/\/github.com\//' -i .gitmodules
- git submodule update --init --recursive || echo "yes"
script:
- make
- ./test/test.py --submodules dronekit-la-testdata
env:
  global:
  - LANG="en_US.UTF-8"
