language: cpp
compiler:
- clang
os: linux
dist: trusty
git:
  submodules: false
before_install:
- echo $LANG
- echo $LC_ALL
- echo $TRAVIS_OS_NAME
- uname -s
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- sed -e 's/git@github.com:/git:\/\/github.com\//' -i .gitmodules
- git submodule update --init --recursive || echo "yes"
- sudo apt-get install -y python-dev python-pip doxygen # for docs
- sudo easy_install -U pip
- pip install --user -r requirements.txt
- pip install --user breathe
script:
- make
- ./test/test.py --submodules dronekit-la-testdata
- doxygen doxygen/doxygen.conf
- cd docs && make html
env:
  global:
  - LANG="en_US.UTF-8"
